### ISSUE TITLE
Improve dependencies installation process

### ISSUE THREAD

**Issue by yorek** [Azure-Samples/azure-sql-db-django#1]
AFAIK it is a best practice in python to use virtualenv to create a virtual envirenment where to install all packages:

https://virtualenv.pypa.io/en/latest/

so that one can just create a virtual enviroment and enabled it

```
virtualenv venv
. ./venv/bin/activate
```

also, I suggest to put all the required packages in a `requirements.txt` file so that you can lock the version and make it easier to install. for example the `requirements.txt` file could be:

```
django==4.0.1
djangorestframework==3.13.1
django-cors-headers==3.11.0
```

and then all those dependencies can be installed just doing

```
pip install -r requirements
```

**Comment by abhimantiwari** [comment]
Yes, you are right, running python apps inside virtual environment is the ideal way to avoid any updates/ installations breaking the apps in future. Added steps for virttualenv. 
Will discuss with you on requirements.txt for one command installation.

**Comment by abhimantiwari** [comment]
Done
