### ISSUE TITLE
Markdown !Directives

### ISSUE THREAD

**Issue by yorek** [Azure-Samples/azure-sql-db-django#12]
It seems that GitHub doesn't support the "!" directives like [!NOTE]. I guess we can just remove them or replace them with something else?

**Comment by abhimantiwari** [comment]
It appears fine on docs preview which simulates the docs.microsoft.com but for GitHub we can replace all "!" directives with simple "> " ?

**Comment by yorek** [comment]
Ah great, didn't know that, perfect then :) If they appear fine on docs.microsoft.com let's leave them
