### ISSUE TITLE
No "azure-create-sql-db.sh"

### ISSUE THREAD

**Issue by yorek** [Azure-Samples/azure-sql-db-django#4]
In the readme there is a reference to the script `azure-create-sql-db.sh` but there is no such script in the repo

**Comment by abhimantiwari** [comment]
Good catch...that was copy/paste issue. Removed that part and updated the docs to read as below...
.....
## Create the Azure SQL Database

If you don't have an Azure SQL server already, you can create one (no additional costs for a server) running the following [AZ CLI](https://docs.microsoft.com/en-us/cli/azure/) command (via [WSL](https://docs.microsoft.com/en-us/windows/wsl/), or Linux or [Azure Cloud Shell](https://azure.microsoft.com/en-us/features/cloud-shell/)):

Create a resource group if you don't have one already created:

```azurecli
az group create -l <location> -n <MyResourceGroup>
```

Create the Database Server:

```azurecli
az sql server create -n <server-name> -l <location> --admin-user <admin-user> --admin-password <admin-password> -g <resource-group>
```

>Make sure to note the database name, username and password somewhere safe.

Create a new Azure SQL database:

```azurecli
az sql db create -g <resource-group> -s <server-name> -n my-db --service-objective GP_Gen5_2
```

Make sure you have the firewall configured to allow your machine to access Azure SQL:

```azurecli
az sql server firewall-rule create --resource-group <resource-group> --server <server-name> --name AllowMyClientIP_1 --start-ip-address <your_public_ip> --end-ip-address <your_public_ip>
```

You can get your public IP [here](https://ipinfo.io/ip) or through other ways, for example: https://ifconfig.me/
