### ISSUE TITLE
Missing mssql dependency

### ISSUE THREAD

**Issue by yorek** [Azure-Samples/azure-sql-db-django#6]
There must be some dependency missing as if I try to run django as described in the readme (`python manage.py runserver`), I get this error:

```
django.core.exceptions.ImproperlyConfigured: 'mssql' isn't an available database backend or couldn't be imported. Check the above exception. To use one of the built-in backends, use 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
```

I guess something like `pyodbc` and `mssql-django` must be installed also, right? Make sure to include them into the `requirements.txt` file and call them out in the readme too.

**Comment by abhimantiwari** [comment]
Yes, you are absolutely right, we need to have `pyodbc` and `mssql-django` installed too.  Did you follow these steps in README.md? Will include them in requirement.txt too.

## Configure Azure SQL connectivity with Django

### Dependencies

- pyodbc 3.0 or newer

### Installation

- Install pyodbc:

    ```python
    pip install pyodbc
    ```

- Install mssql-django:

    ```python
    pip install mssql-django
    ```

### Configuration

Configure the Database ConnectionString in the settings.py file used by your Django application or project:

```sql
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'Database_name',
        'HOST': "xyz.database.windows.net",
        'PORT': '1433',
        'USER': 'User_name',
        'PASSWORD': 'db_pwd',
        'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
            },
    }
}
```

To connect Azure SQL DB using MSI (Managed Service Identity), you can have settings as below:

```sql
DATABASES = {
    'default': {
         'ENGINE': 'mssql',
         'HOST': 'xyz.database.windows.net',
         'NAME': 'Database_name', 
         'PORT': '', 
         'Trusted_Connection': 'no', 
         'OPTIONS': { 
             'driver': 'ODBC Driver 17 for SQL Server', 
             'extra_params': "Authentication=ActiveDirectoryMsi;Encrypt=yes;TrustServerCertificate=no" }
     }
}
```

> [!WARNING]
> [mssql-django](https://github.com/microsoft/mssql-django) doesn't support using time zones so the recommendation is to ensure the `USE_TZ` option is set to `False`.

```sql
DATABASES = {
...
}

# set this to False if the backend does not support using time zones
USE_TZ = False
```

**Comment by yorek** [comment]
Yeah, I did not see that part of the readme. ss soon as I tried to run the clone repo, I got those errors and stopped reading further. I think that now that we have reorganized the readme is clear enough.
