### ISSUE TITLE
Login timeout expired

### ISSUE THREAD

**Issue by yorek** [Azure-Samples/azure-sql-db-django#7]
After having managed to have all dependencies correctly installed, if I just run `python manage.py runserver` I get the following error:

```
django.db.utils.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
```

it seems there is some configuration needed, but it is not specified in the readme.

**Comment by abhimantiwari** [comment]
Got it, it is expected when application fails to connect to database due to certain issues like firewall block, idle DB (serverless) etc. and time-out the remote connection. Will check all these issues in our call today. :-)

**Comment by yorek** [comment]
Closing as it is now fixed

**Comment by mengjiewarmuth** [comment]
Hi, how did you solve this problem? I get the same problem and  spend already 2 days for it.  Thank you for the help.

**Comment by abhimantiwari** [comment]
@mengjiewarmuth Are you able to connect to the database from local machine using SSMS, ADS etc? Please make sure that ODBC driver and other dependencies are configured properly.

**Comment by mengjiewarmuth** [comment]
Hi,
thanks for your reply. Yes, I can connect to the database from a local
machine using ADS. But after I run python manage.py runserver, I get the
same error message.
warm regards
Mengjie Warmuth

Am Di., 22. Feb. 2022 um 09:25 Uhr schrieb Abhiman Tiwari <
***@***.***>:

**Comment by abhimantiwari** [comment]
@mengjiewarmuth I would suggest you create a new virtual environment and follow all the steps again from beginning and make sure that you install all the dependencies correctly. Also make sure you create **.env** file, using the provided .env.sample, to provide database connection info.
